version: 2
jobs:
 build:
  docker:
   - image: holochain/holonix
  steps:
   - checkout

   - run:
      name: run the tests
      command: nix-shell --run 'cargo test'

workflows:
 version: 2
 build:
  jobs:
   - build
